### ISSUE TITLE
Swedbank clearing numbers should not be five digits

### ISSUE THREAD

**Issue by aaalvik** [insurello/elm-swedish-bank-account-number#10]
## Background
I am using this library in a form on vy.se and we have some trouble with Swedbank clearing numbers.

According to the customer service people I have spoken to at Vy Sweden, all clearing numbers should only contain four digits and therefore the form field should only accept four digit clearing numbers. 

Some banks, like Swedbank, operate with an extra digit behind the clearing number, like XXXX-Y, but the way I understand this is that the Y is not a part of the actual clearing number and should not be included in the validation process. Meaning that Swedbank customers should only insert the first four digits (XXXX) into the form and should ignore the last one (Y) since this part is only used internally by Swedbank. **If this is correct, then the validation for Swedbank Type 2 clearing numbers should be altered to accept all digits in the range 8000-8999.** 

## Problem
The validation of Swedbank clearing numbers should only check the first four digits. Today it accepts a clearing number like `8420-2` and fails when given the actual clearing number part; `8420`, which it should not. 

![bilde](https://user-images.githubusercontent.com/15728964/158798526-204c90b1-0abd-4585-b03f-b90b222993bb.png)

**Comment by lydell** [comment]
Hi!

I googled for “swedbank clearingnummer” and got this as the first match:

https://www.swedbank.se/privat/betala-och-overfora/konton/clearingnummer.html

> Clearingnummer i Swedbank börjar antingen på siffran 7 och består av fyra siffror eller på **siffran 8 och består av fem siffror.**

That’s why we went with this implementation:

https://github.com/insurello/elm-swedish-bank-account-number/blob/575e995ec13ae4183812f7e258a046b5311f3195/src/SwedishBankAccountNumber/Bank.elm#L392-L399

**Comment by aaalvik** [comment]
Thank you for your quick reply! I agree with your conclusion after reading the Swedbank-description and will try to explain this to the customer service people 😊

**Comment by aaalvik** [comment]
Hello again, 

I spoke to the customer service people again, and they pointed out this note on Swedbank's homepage (in one of the toggle points further down on the same page that you linked above):

> Generellt brukar det vara så andra banker bara använder fyra siffror i clearingnumret. 
> 
> Om du har fem siffror i clearingnumret så tar man bort den femte siffran, den som är efter strecket, om någon som har en annan bank än Swedbank eller en sparbank ska sätta in pengar till dig.
> 
> Exempel: 8xxx-x 

This seems to me that the validation should accept 4-digit clearing numbers from Swedbank as well, or what do you think? :)

**Comment by lydell** [comment]
To me, that sounds like instructions on how to deal with/workaround non-Swedbank UIs that wrongly assume that clearing numbers always are 4 digits.

If you want the best user experience on vy.se, wouldn’t that be to let your Swedbank users enter the 5-digit clearing number in one box and the account number in another?

The way I fill in bank accounts on the web is by logging in on my bank, clicking on an account and hunt for a place where they show the numbers.

This is what that looks like for my own Swedbank account (I replaced most numbers with X for privacy):

<img width="458" alt="image" src="https://user-images.githubusercontent.com/2142817/159303747-2ab5724f-70f0-4d55-a352-2b66b5a7ceb7.png">

So if I’m on a website that asks me for clearing number and account number, I’d just paste those 5 digits in one box and the rest in the other. I wouldn’t expect that “oh, this is a non-Swedbank site, so I’ll paste just for digits in the first box and move over the fifth to the other”. Because I don’t know how long a clearing number is, and I don’t think a random Swede does either.

One last thought: I guess you could do string slicing in your app if you want to always have 4 digits as clearing number somewhere?

**Comment by lydell** [comment]
I tried adding my Swedbank account on another bank as a saved recipient. I entered just the first 4 clearing digits. After I clicked “Save”, it calculated the fifth digit for me.

Is that what you’d expect from this package as well?

- Allow entering just 4 digits, calculate the fifth. `toRecord` and `ClearingNumber.toString` returns the clearing number with all 5 digits.
- Also allow entering 5 digits, check that the fifth is correct. (current behavior)

**Comment by aaalvik** [comment]
I use this library in a form where customers can apply for a refund after a delayed train journey. The customer services that receive the filled out forms tell me that they only ever need four digits also for Swedbank, so in my use case I don't even need to calculate the fifth control digit :) 

So at least for me it would work perfectly with the last approach you're suggesting!

**Comment by lydell** [comment]
Are you up for calculating the fifth digit yourself for Swedbank to start with then, and coming back later with results?

1. Read user input.
2. Remove non-digits.
3. If four digits and the first one is 8, calculate the fifth and feed that to this package. Otherwise, feed as-is to this package.

**Comment by aaalvik** [comment]
Ah, I guess I misunderstood you. The optimal solution for me would be if the validation would accept also four digits for Swedbank and not have to care about the fifth digit, because I will neither ask the user to insert the fifth one (I restrict the input field to four digits), not will i send a fifth digit through to the receivers of the form (they will only accept the first four digits no matter what bank). 

But did you think that was a bad idea?

**Comment by lydell** [comment]
That would be the optimal solution yes (probably), but I thought it could be nice to “try before buy”. So we could start with you “working around it” in your code, and if that ends up successful we’ll make changes here. What do you think?

**Comment by aaalvik** [comment]
Aah yes, I understand! I will try that out 😊

**Comment by lydell** [comment]
How did it go in the end? Do you have any code to share?

**Comment by aaalvik** [comment]
It worked perfectly when I computed the fifth digit before feeding it to the package 🎉

**Comment by lydell** [comment]
Nice! Status update: I think it would make sense to support automatically calculating the fifth digit for Swedbank is missing, like we’ve discussed, but I don’t know when it’ll happen (not a priority for us, and there’s a workaround).

**Comment by aaalvik** [comment]
Agreed. Should I close this issue or keep it open until you get the time to look at it? :)

**Comment by lydell** [comment]
We’ll leave it open :)

**Comment by lydell** [comment]
I looked into some bank stuff today, and found one more customer-facing documentation page at Swedbank: https://www.swedbank.se/privat/betala-och-overfora/konton/clearingnummer/5-siffriga-clearingnummer-som-borjar-pa-siffran-8.html

> Hur du ska skriva bankkontonumret vid en överföring beror på vilken bank du har. Detta då bankerna har olika system som kräver olika antal siffror - vanligen 14 eller 15. Är det färre siffror så fyller du på med nollor mellan clearingnumret och kontonumret. Det finns 2 huvudsakliga sätt att skriva bankkontonummer när clearingnumret börjar på siffran 8:
>
> - Ha kvar den femte siffran (gäller vid överföringar från de flesta banker idag)
> - Ta bort den femte siffran (gäller överföringar från ett fåtal banker idag)

> How you write the bank account number for a transfer depends on which bank you have. This is because the banks have different systems that require different numbers of numbers - usually 14 or 15. If there are fewer numbers, you add zeros between the clearing number and the account number. There are 2 main ways to write the bank account number when the clearing number starts with the digit 8:
>  
> - Keep the fifth digit (valid for transfers from most banks today)
> - Remove the fifth digit (applies to transfers from a few banks today)

I also tested making transfers in some more banks myself. Only 1 of 4 allowed entering just 4 digits (it accepted both 4 and 5).

We also have a lot of Swedbank customers at Insurello. I talked to our Customer Service once, and they did not recognize “number of digits in Swedbank clearing numbers” as a problem.

My conclusion is that using the full 5 digits is the norm these days, while using 4 is the exception.

So I’m closing this. As repetition, the algorithm for calculating just 4 digits oneself is here: https://github.com/insurello/elm-swedish-bank-account-number/issues/10#issuecomment-1074842470
